//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_progress_report
{
    public partial class AdminLogin
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox AdminIdTextBox;
        protected global::System.Web.UI.WebControls.TextBox PasswordTextBox;
        protected global::System.Web.UI.WebControls.Button LoginButton;
        protected global::System.Web.UI.WebControls.Label StatusLabel;
    }
}
