//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_progress_report
{
    public partial class Register
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.RadioButtonList UserTypeRadioButtonList;
        protected global::System.Web.UI.WebControls.Panel RegistrationPanel;
        protected global::System.Web.UI.WebControls.TextBox FirstNameTextBox;
        protected global::System.Web.UI.WebControls.TextBox LastNameTextBox;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl IDLabel;
        protected global::System.Web.UI.WebControls.TextBox IDTextBox;
        protected global::System.Web.UI.WebControls.DropDownList GenderDropDownList;
        protected global::System.Web.UI.WebControls.DropDownList DepartmentDropDownList;
        protected global::System.Web.UI.WebControls.TextBox DOBTextBox;
        protected global::System.Web.UI.WebControls.Panel StudentPanel;
        protected global::System.Web.UI.WebControls.DropDownList YearDropDownList;
        protected global::System.Web.UI.WebControls.DropDownList SemesterDropDownList;
        protected global::System.Web.UI.WebControls.FileUpload PhotoFileUpload;
        protected global::System.Web.UI.WebControls.Button SubmitButton;
        protected global::System.Web.UI.WebControls.Label StatusLabel;
    }
}
