//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_progress_report {
    
    
    public partial class UserDashboard {
        
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label UserNameLabel;
        protected global::System.Web.UI.WebControls.Button LogoutButton;
        
        protected global::System.Web.UI.WebControls.TextBox SearchDeptTextBox;
        protected global::System.Web.UI.WebControls.TextBox SearchCourseTextBox;
        protected global::System.Web.UI.WebControls.TextBox SearchTopicTextBox;
        protected global::System.Web.UI.WebControls.Button SearchButton;
        protected global::System.Web.UI.WebControls.Label SearchStatusLabel;
        protected global::System.Web.UI.WebControls.GridView SearchResultsGrid;
        
        protected global::System.Web.UI.WebControls.Label UploadStatusLabel;
        protected global::System.Web.UI.WebControls.TextBox UploadDeptTextBox;
        protected global::System.Web.UI.WebControls.TextBox UploadCourseTextBox;
        protected global::System.Web.UI.WebControls.TextBox UploadTopicTextBox;
        protected global::System.Web.UI.WebControls.FileUpload ResourceFileUpload;
        protected global::System.Web.UI.WebControls.Button UploadButton;
        
        protected global::System.Web.UI.WebControls.GridView MyUploadsGrid;
        protected global::System.Web.UI.WebControls.GridView MyDownloadsGrid;
    }
}
